services:
    keycloak:
        image: quay.io/keycloak/keycloak:24.0.1
        container_name: grizzl-keycloak
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./keycloak-config:/opt/keycloak/data/import
        command: start-dev --import-realm
