services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.3.4
        container_name: grizzl-keycloak
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./keycloak-config:/opt/keycloak/data/import
        command: start-dev --import-realm

    webserver:
        image: "node:24.8-alpine3.22"
        container_name: grizzl-webserver
        build:
            args:
                APP_ENV: "development"
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        command: npm run dev
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        depends_on:
            keycloak:
                condition: service_started