services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.3.4
        container_name: grizzl-keycloak
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import:ro
        command: start-dev --import-realm

    webserver:
        image: "node:24.8-alpine3.22"
        container_name: grizzl-webserver
        build:
            args:
                APP_ENV: "development"
        restart: unless-stopped
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        command: npm run dev
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        depends_on:
            - keycloak

    caddy:
        image: caddy:2.8
        container_name: grizzl-caddy
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - webserver
