services:
    setup:
        image: node:24.8-alpine3.22
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        command: npm install

    keycloak:
        image: quay.io/keycloak/keycloak:26.3.4
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
            KC_HOSTNAME: http://keycloak.grizzl.localhost
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import:ro
        command: start-dev --import-realm

    webserver:
        image: node:24.8-alpine3.22
        build:
            args:
                APP_ENV: development
        restart: unless-stopped
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        command: npm run dev
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        depends_on:
            keycloak:
                condition: service_started
            setup:
                condition: service_completed_successfully

    playwright:
        image: mcr.microsoft.com/playwright:v1.55.1-noble
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        environment:
            - DISPLAY=${DISPLAY}
            - TZ=Europe/Berlin
        network_mode: "host"
        ipc: host
        devices:
            - /dev/dri

    caddy:
        image: caddy:2.10-alpine
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - webserver
