x-public: &public
    NUXT_PUBLIC_APP_ENV: test
    NUXT_PUBLIC_VERSION: ${NUXT_PUBLIC_VERSION}
    NUXT_PUBLIC_ORIGIN: ${NUXT_PUBLIC_ORIGIN}
    NUXT_PUBLIC_LEGAL_EMAIL: ${NUXT_PUBLIC_LEGAL_EMAIL}
    NUXT_PUBLIC_LEGAL_PHONE: ${NUXT_PUBLIC_LEGAL_PHONE}
    NUXT_PUBLIC_LEGAL_RESPONSIBLE_ENTITY: ${NUXT_PUBLIC_LEGAL_RESPONSIBLE_ENTITY}
    NUXT_PUBLIC_LEGAL_STREET: ${NUXT_PUBLIC_LEGAL_STREET}
    NUXT_PUBLIC_LEGAL_ZIP_AND_CITY: ${NUXT_PUBLIC_LEGAL_ZIP_AND_CITY}

services:
    postgres:
        container_name: grizzl-postgres
        image: postgres:18.0-alpine3.22
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: admin
            DB_NAME: grizzl
            DB_PASSWORD: password
            DB_USERNAME: grizzl_user
        volumes:
            - grizzl_database:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin"]
            interval: 1s
            timeout: 15s
            retries: 10

    migrations:
        image: node:24-alpine
        container_name: grizzl-migrations
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        environment:
            DB_HOST: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            DB_NAME: grizzl
        command: npx drizzle-kit migrate
        restart: "no"

    webserver:
        container_name: grizzl-web-server
        build:
            context: .
            dockerfile: Dockerfile
            args:
                <<: *public
        environment:
            <<: *public
            DB_HOST: ${DB_HOST}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
            BETTER_AUTH_URL: ${BETTER_AUTH_URL}
            OAUTH_GITHUB_ID: ${OAUTH_GITHUB_ID}
            OAUTH_GITHUB_SECRET: ${OAUTH_GITHUB_SECRET}
            OAUTH_DISCORD_ID: ${OAUTH_DISCORD_ID}
            OAUTH_DISCORD_SECRET: ${OAUTH_DISCORD_SECRET}
            OAUTH_REDDIT_ID: ${OAUTH_REDDIT_ID}
            OAUTH_REDDIT_SECRET: ${OAUTH_REDDIT_SECRET}
            OAUTH_TWITCH_ID: ${OAUTH_TWITCH_ID}
            OAUTH_TWITCH_SECRET: ${OAUTH_TWITCH_SECRET}
        restart: no
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        depends_on:
            postgres:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully
            keycloak:
                condition: service_healthy

    keycloak:
        container_name: grizzl-keycloak
        build:
            context: ./docker/keycloak
            dockerfile: Dockerfile
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import:ro
        command: start-dev --import-realm
        healthcheck:
            test: ["CMD-SHELL", "curl --head -fsS http://localhost:8080/realms/dev-test/"]
            interval: 5s
            timeout: 60s
            retries: 12

    playwright:
        container_name: grizzl-playwright-dev
        image: mcr.microsoft.com/playwright:v1.57.0-noble
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        network_mode: "service:caddy"
        environment:
            - TZ=Europe/Berlin
            - CI=true

    caddy:
        container_name: grizzl-caddy-dev
        image: caddy:2.10-alpine
        user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
        restart: unless-stopped
        extra_hosts:
            - "grizzl.localhost:127.0.0.1"
        ports:
            - "80:80"
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
        depends_on:
            - webserver
            - keycloak

volumes:
    grizzl_database:
        name: grizzl_database
