services:
    postgres:
        container_name: grizzl-postgres
        image: postgres:18.0-alpine3.22
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: admin
            DB_NAME: grizzl
            DB_PASSWORD: password
            DB_USERNAME: grizzl_user
        volumes:
            - grizzl_database:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 1s
            timeout: 15s
            retries: 10

    migrations:
        image: node:24-alpine
        container_name: grizzl-migrations
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/home/grizzl
        working_dir: /home/grizzl
        environment:
            DB_HOST: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            DB_NAME: grizzl
        command: npx drizzle-kit migrate
        restart: "no"

    keycloak:
        container_name: grizzl-keycloak
        image: quay.io/keycloak/keycloak:26.3.4
        environment:
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        ports:
            - "8080:8080"
        volumes:
            - ./docker/keycloak:/opt/keycloak/data/import:ro
        command: start-dev --import-realm

volumes:
    grizzl_database:
        name: grizzl_database
