import {
    ICON_ARROW_DOWN,
    ICON_ARROW_LEFT,
    ICON_ARROW_RIGHT,
    ICON_ARROW_UP,
    ICON_ARROW_UP_RIGHT,
    ICON_CANCEL,
    ICON_CANCEL_CIRCLE,
    ICON_CHECK,
    ICON_CHECK_CIRCLE,
    ICON_CHEVRON_DOWN,
    ICON_CHEVRON_LEFT,
    ICON_CHEVRON_RIGHT,
    ICON_CHEVRON_UP,
    ICON_CIRCLE_ALERT,
    ICON_COMPUTER,
    ICON_COPY,
    ICON_COPY_CHECK,
    ICON_DOUBLE_CHEVRON_LEFT,
    ICON_DOUBLE_CHEVRON_RIGHT,
    ICON_DRAG_VERTICAL,
    ICON_ELLIPSIS_HORIZONTAL,
    ICON_EYE,
    ICON_EYE_OFF,
    ICON_FILE,
    ICON_FOLDER,
    ICON_FOLDER_OPEN,
    ICON_HASH,
    ICON_INFO,
    ICON_LIGHTBULB,
    ICON_LOAD,
    ICON_MENU,
    ICON_MINUS,
    ICON_MOON,
    ICON_PANEL_CLOSE,
    ICON_PANEL_OPEN,
    ICON_PLUS,
    ICON_RESTART,
    ICON_SEARCH,
    ICON_STOP,
    ICON_SUN,
    ICON_UPLOAD,
    ICON_WARNING,
} from "./core/constants/icons.constant";

export default defineAppConfig({
    ui: {
        inputNumber: {
            variants: {
                size: {
                    md: "px-2.5 py-1.5 text-sm gap-1.5",
                    lg: "px-3 py-2 text-sm gap-2",
                },
            },
        },
        input: {
            variants: {
                size: {
                    md: {
                        base: "px-2.5 py-1.5 text-sm gap-1.5",
                    },
                    lg: {
                        base: "px-3 py-2 text-sm gap-2",
                    },
                },
            },
        },
        pinInput: {
            variants: {
                size: {
                    md: {
                        base: "size-8 text-sm",
                    },
                    lg: {
                        base: "size-9 text-sm",
                    },
                },
            },
        },
        icons: {
            arrowUp: ICON_ARROW_UP,
            arrowRight: ICON_ARROW_RIGHT,
            arrowLeft: ICON_ARROW_LEFT,
            arrowDown: ICON_ARROW_DOWN,
            caution: ICON_CIRCLE_ALERT,
            check: ICON_CHECK,
            chevronDoubleLeft: ICON_DOUBLE_CHEVRON_LEFT,
            chevronDoubleRight: ICON_DOUBLE_CHEVRON_RIGHT,
            chevronDown: ICON_CHEVRON_DOWN,
            chevronLeft: ICON_CHEVRON_LEFT,
            chevronRight: ICON_CHEVRON_RIGHT,
            chevronUp: ICON_CHEVRON_UP,
            close: ICON_CANCEL,
            copy: ICON_COPY,
            copyCheck: ICON_COPY_CHECK,
            dark: ICON_MOON,
            drag: ICON_DRAG_VERTICAL,
            ellipsis: ICON_ELLIPSIS_HORIZONTAL,
            error: ICON_CANCEL_CIRCLE,
            external: ICON_ARROW_UP_RIGHT,
            eye: ICON_EYE,
            eyeOff: ICON_EYE_OFF,
            file: ICON_FILE,
            folder: ICON_FOLDER,
            folderOpen: ICON_FOLDER_OPEN,
            hash: ICON_HASH,
            info: ICON_INFO,
            light: ICON_SUN,
            loading: ICON_LOAD,
            menu: ICON_MENU,
            minus: ICON_MINUS,
            panelClose: ICON_PANEL_CLOSE,
            panelOpen: ICON_PANEL_OPEN,
            plus: ICON_PLUS,
            reload: ICON_RESTART,
            search: ICON_SEARCH,
            stop: ICON_STOP,
            success: ICON_CHECK_CIRCLE,
            system: ICON_COMPUTER,
            tip: ICON_LIGHTBULB,
            upload: ICON_UPLOAD,
            warning: ICON_WARNING,
        },
    },
});
