CREATE ROLE grizzl_user LOGIN PASSWORD 'super-secure-password';
GRANT CONNECT ON DATABASE grizzl TO grizzl_user;

GRANT USAGE ON SCHEMA public TO grizzl_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO grizzl_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO grizzl_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO grizzl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO grizzl_user;
